GENOME_REF: "/projects/sbrown_prj/220318_DI/data/raw/ref/GRCh37.p13.genome.fa"
ENV: "/projects/nknoetze_prj/ocr_prj/src/tcell_ocr_prj/framework_env.yaml"
OCRMETRICS_DATA_DIR: "/projects/sbrown_prj/sbrown_scratch/220318_DI/data/raw/ocrs/ZoE_allbutmotifs"

TARGET_GENES: "/projects/sbrown_prj/220318_DI/data/interim/tcell_gene_lists/4sigma_target_genes_231006.txt"
BACKGROUND_GENES: "/projects/sbrown_prj/220318_DI/data/interim/tcell_gene_lists/3sigma_background_genes_231006.txt"
REGIONS: "/projects/nknoetze_prj/ocr_prj/results/ocr_metric_files/meuleman_tcell_2sample_1cd8_1cd4_ocrs_merged/Loop_2.5kb/merged_interactions/connectivity8/tss_within/pulled_ocrs_tss_dist.tsv"
ALL_GENES: "/projects/sbrown_prj/sbrown_scratch/220318_DI/data/raw/ocrs/ranked_gene_list.tsv"

NUM_ITER: 10000
CORES: 64

FUNCTIONS: "fimo_geneCount"

FIMO_DATA: "/projects/sbrown_prj/220318_DI/data/processed/novel_kmer/230710/JASPAR+novelPCallArchetypes.meme"
EXPRESSED_TFS: "/projects/nknoetze_prj/references/annotations/tf_fantom/fantom5_tf_hg19_expressed.tsv"

NUM_MOTIFS: [1]
MAX_BACKGROUND_WRITTEN: 100

OUTPUT: "/projects/sbrown_prj/220318_DI/data/processed/tcell_ocr_metrics/ZoE_single+allbutmotifs_10k/results_231025.tsv"